spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

# 路由包路径
missyou:
  api-package: pro.kelu.missyou.api


# 微信配置
wx:
  appid: wxbe01d607d47d091e
  appsecret: b4242ed6211fd7f77d1d41d2a7af3093
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code